"""campos admin master empresa

Revision ID: 4be5e1b44062
Revises: 304700cf87ac
Create Date: 2026-06-24 00:18:37.544579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be5e1b44062'
down_revision = '304700cf87ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_mensalidade', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('data_vencimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status_pagamento', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('status_pagamento')
        batch_op.drop_column('data_vencimento')
        batch_op.drop_column('valor_mensalidade')

    # ### end Alembic commands ###
